apiVersion: v1
kind: Pod
metadata: 
  name: pd1
spec:
  containers:
  - name: c1
    image: nginx
    env:
    - name: DB_IP_READ
      valueFrom:
        configMapKeyRef:
          key: DB_IP
          name: config
